# General
column_limit: 140
indent_width: 4
use_tab: false
tab_width: 4
continuation_indent_width: 4
spaces_before_call: 1
keep_simple_control_block_one_line: false
break_after_operator: true
double_quote_to_single_quote: true
single_quote_to_double_quote: false
spaces_around_equals_in_field: true
line_separator: input

# Function
break_after_functiondef_lp: false
break_before_functiondef_rp: true

break_after_functioncall_lp: false
break_before_functioncall_rp: true

spaces_inside_functioncall_parens: false
spaces_inside_functiondef_parens: false

align_args: true
align_parameter: true

line_breaks_after_function_body: 1

keep_simple_function_one_line: false

chop_down_parameter: true

# Table
chop_down_table: true
chop_down_kv_table: true

break_after_table_lb: true
break_before_table_rb: true

column_table_limit: 100
column_table_limit_kv: 100

extra_sep_at_table_end: false
spaces_inside_table_braces: true

table_sep: ","

align_table_field: true